# Generated by Django 3.0.4 on 2021-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20210413_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(default='Jain Option Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='sushi_name'),
        ),
    ]
