# Generated by Django 3.0.4 on 2021-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210515_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='instructions',
            field=models.CharField(default='Cash on delivery Option Available', max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='item_name'),
        ),
    ]
